# Generated by Django 4.2.7 on 2024-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active')], default='pending', max_length=20),
        ),
    ]
