# Generated by Django 4.2.7 on 2024-07-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Aending'), ('active', 'Active')], default='Pending', max_length=20),
        ),
    ]
