# Generated by Django 4.2.7 on 2024-07-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patient_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='bate_of_birth',
            new_name='Date_of_birth',
        ),
    ]
