# Generated by Django 4.2.7 on 2024-07-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_bate_of_birth_patient_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_Name', models.CharField(max_length=100)),
                ('Date_of_birth', models.CharField(max_length=100)),
                ('experience_level', models.IntegerField()),
                ('age', models.IntegerField()),
                ('specialization', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('status', models.CharField(default='Null', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='last_view',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
