# Generated by Django 4.2.7 on 2024-07-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_doctor_patient_last_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
