# Generated by Django 4.2.7 on 2024-07-09 07:27

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('age', models.DateField()),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\-]+$')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('cancel', 'Cancelled')], default='pending', max_length=10)),
                ('last_visit', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
