# Generated by Django 4.2.7 on 2024-07-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patients_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='address',
            field=models.CharField(default='Address', max_length=200),
        ),
        migrations.AddField(
            model_name='patients',
            name='date_of_birth',
            field=models.CharField(default='YYYY-MM-DD', max_length=12),
        ),
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.EmailField(default='email', max_length=254),
        ),
        migrations.AddField(
            model_name='patients',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Cancel', 'Cancelled')], default='Status', max_length=10),
        ),
    ]
