# Generated by Django 4.2.7 on 2024-07-15 09:30

from django.db import migrations, models
import doctors.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patients_address_patients_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='patien_doctor_name',
            field=models.CharField(default='Doctor Name', max_length=100, verbose_name=doctors.models.Doctors),
        ),
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.IntegerField(blank=True, default='Age', null=True),
        ),
    ]
