# Generated by Django 4.2.7 on 2024-07-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patients_patien_doctor_name_alter_patients_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='patien_doctor_name',
            new_name='patient_doctor_name',
        ),
    ]
