# Generated by Django 4.2.7 on 2024-07-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_rename_patien_doctor_name_patients_patient_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date_of_birth',
            field=models.CharField(default='Date Of Birth', max_length=12),
        ),
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('female', 'female'), ('Other', 'Other')], default='Gender', max_length=10),
        ),
    ]
