# Generated by Django 4.2.7 on 2024-07-09 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\-]+$')])),
                ('specialization', models.CharField(max_length=50)),
                ('availability', models.CharField(choices=[('available', 'available'), ('Not available', 'Not available'), ('Leave', 'leave')], default='available', max_length=20)),
            ],
        ),
    ]
