# Generated by Django 4.2.7 on 2024-07-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctors_address_doctors_age_doctors_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='age',
            field=models.IntegerField(blank=True, default='Age', null=True),
        ),
    ]
